export const applicationList = [
  {
    backgroundImage: require('@/assets/home/video.png'),
    state: 1,
    like: 1,
    name: '视频',
    message: '已加入10个',
    screen: 'Play',
  },
  {
    backgroundImage: require('@/assets/home/second.png'),
    state: 0,
    like: 1,
    // name:'视频',
    // message:'已加入10个',
  },
  {
    backgroundImage: require('@/assets/home/third.png'),
    state: 0,
    like: 1,
    name: '任务',
    message: '已领取：99个',
  },
  {
    backgroundImage: require('@/assets/home/four.png'),
    state: 0,
    like: 1,
    name: '群组',
    message: '已加入10个群组',
  },
  {
    backgroundImage: require('@/assets/home/five.png'),
    state: 0,
    like: 1,
    name: '图文',
    message: '[用户名]在文中@你',
    screen: 'Photo',
  },
  {
    backgroundImage: require('@/assets/home/activity.png'),
    state: 0,
    like: 1,
    name: '活动',
    message: '活动状态改变',
  },
];
