import {StyleSheet} from 'react-native';
import px from '@/util/adaptation';
export default StyleSheet.create({
  screen: {
    backgroundColor: '#000000',
    height: '100%',
    width: '100%',
    opacity: 0.8,
  },
  headerSearch: {
    height: px(60),
    width: '100%',
    fontSize: px(28),
    backgroundColor: '#333333',
  },
  plate: {
    width: px(690),
    marginTop: px(20),
    marginBottom: px(8),
    height: px(224),
    display: 'flex',
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginLeft: px(30),
    marginRight: px(30),
  },
  plateText: {
    fontSize: px(28),
    color: '#FFFFFF',
    marginTop: px(24),
    textAlign: 'center',
  },
  plateItem: {
    width: px(224),
    height: px(224),
  },
  status: {
    display: 'flex',
    alignItems: 'center',
    flexDirection: 'row',
    backgroundColor: '#333333',
    height: px(50),
  },
  statusText: {
    color: '#FFFFFF',
    fontSize: px(24),
    lineHeight: px(50),
  },
  statusText2: {
    color: '#FFFFFF',
    fontSize: px(26),
    lineHeight: px(50),
  },
  first: {
    marginLeft: px(30),
    marginRight: px(29),
  },
  second: {
    marginRight: px(21),
  },
  third: {
    color: '#00D623',
  },
  appList: {
    width: px(690),
    marginLeft: px(30),
    marginRight: px(30),
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    flexDirection: 'row',
    flexWrap: 'wrap',
    flexShrink: 0,
    height: px(148),
    alignContent: 'flex-start',
  },
  application: {
    width: px(340),
    height: px(140),
    marginBottom: px(8),
    position: 'relative',
  },
  appText: {
    fontSize: px(26),
    color: '#FFFFFF',
    marginTop: px(41),
    marginBottom: px(16),
    marginLeft: px(20),
  },
  appMessage: {
    fontSize: px(20),
    color: '#FFFFFF',
    marginLeft: px(20),
  },
  star: {
    width: px(24),
    height: px(24),
    position: 'absolute',
    right: px(18),
    top: px(18),
  },
  select: {
    width: px(30),
    height: px(30),
    position: 'absolute',
    right: px(19),
    bottom: px(18),
  },
});
