import px from '@/util/adaptation';
import {StyleSheet, Platform, Dimensions} from 'react-native';
const statusHeight = Platform.OS == 'android' ? 0 : px(57);
const height = Dimensions.get('window').height;
export default StyleSheet.create({
  container: {
    width: '100%',
    height,
  },
  slide1: {
    backgroundColor: '#000000',
    opacity: 0.8,
    paddingTop: statusHeight + px(26),
    height,
    display: 'flex',
    flexDirection: 'column',
  },
  header: {
    width: '100%',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    height: px(32),
  },
  rightIconList: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'flex-end',
    flexDirection: 'row',
  },
  headIcon: {
    width: px(32),
    height: px(32),
  },
  headTit: {
    color: '#fff',
    fontSize: px(30),
    fontWeight: 'bold',
    marginLeft: px(31),
  },
  contentText: {
    width: px(690),
    marginLeft: px(31),
    marginTop: px(17),
    marginRight: px(30),
    marginBottom: px(15),
  },
  texts:{
    fontSize: px(26),
    color: '#FFFFFF',
  },
  starPeople: {
    fontSize: px(26),
    color: '#FF460B',
    marginLeft: px(31),
    marginBottom: px(17),
  },
  showMore: {
    color: '#36A8FF',
    fontSize: px(26),
  },
  horn: {
    width: px(72),
    height: px(60),
    borderBottomLeftRadius: px(30),
    borderTopLeftRadius: px(30),
    backgroundColor: '#000000',
    opacity: 0.2,
    position: 'absolute',
    top: px(30),
    right: 0,
  },
  icon: {
    width: px(36),
    height: px(30),
    position: 'absolute',
    top: px(44),
    right: px(12),
  },
  open: {
    width: px(16),
    height: px(200),
    position: 'absolute',
    top: px(259),
  },
  photoList: {
    width: '100%',
    height: px(56),
    display: 'flex',
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'flex-start',
    position: 'absolute',
    left: px(30),
    bottom: px(379),
    borderRadius: px(4),
  },
  avatar: {
    position: 'absolute',
    right: px(31),
    bottom: px(379),
  },
  controller: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    zIndex: 20,
    paddingBottom: px(41),
    backgroundColor: '#000000',
    opacity: 0.84,
    width: '100%',
    minHeight: px(316),
    paddingLeft: px(30),
  },
  head: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'flex-start',
    flexDirection: 'row',
    width: '100%',
  },
  comment: {
    width: px(88),
    height: px(36),
    borderWidth: px(2),
    borderColor: '#FF4646',
    borderRadius: px(10),
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    flexDirection: 'row',
    marginRight: px(8),
  },
});
