import {scaleSizeW, scaleSizeH, setSpText} from '@/util/adaptation';
import {StyleSheet, Platform, Dimensions} from 'react-native';
const statusHeight = Platform.OS == 'android' ? 0 : scaleSizeH(57);
const height = Dimensions.get('window').height;
export default StyleSheet.create({
  container: {
    flex: 1,
  },
  rightIconList: {
    display: 'flex',
    justifyContent: 'flex-end',
    flexDirection: 'row',
    marginRight: scaleSizeW(34),
    marginLeft: 'auto',
    marginTop: scaleSizeH(26) + statusHeight,
    marginBottom: scaleSizeH(45),
  },
  headIcon: {
    width: setSpText(32),
    height: setSpText(32),
  },
  horn: {
    width: setSpText(72),
    height: setSpText(60),
    borderBottomLeftRadius: setSpText(30),
    borderTopLeftRadius: setSpText(30),
    backgroundColor: '#000000',
    opacity: 0.2,
    position: 'absolute',
    top: scaleSizeH(147),
    right: 0,
  },
  videoStatus: {
    width: setSpText(119),
    height: setSpText(119),
    marginTop: scaleSizeH(315),
    marginLeft: 'auto',
    marginRight: 'auto',
  },
  icon: {
    width: setSpText(36),
    height: setSpText(30),
    marginLeft: 'auto',
    marginRight: scaleSizeW(12),
  },
  open: {
    width: scaleSizeW(16),
    height: scaleSizeH(200),
    position: 'absolute',
    top: scaleSizeH(566),
  },
  avatar: {
    position: 'absolute',
    right: scaleSizeW(31),
    bottom: scaleSizeH(343),
  },
  controller: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    zIndex: 20,
    backgroundColor: '#000000',
    opacity: 0.84,
    width: '100%',
    minHeight: scaleSizeH(316),
    paddingLeft: scaleSizeW(30),
  },
  head: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'flex-start',
    flexDirection: 'row',
    width: '100%',
  },
  comment: {
    width: scaleSizeW(88),
    height: scaleSizeH(36),
    borderWidth: scaleSizeW(2),
    // borderColor: '#FF4646',
    borderRadius: scaleSizeW(10),
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    flexDirection: 'row',
    marginRight: scaleSizeW(8),
  },
  backgroundVideo: {
    width: '100%',
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    height: height - scaleSizeH(316),
    backgroundColor: 'black',
    opacity: 0.8,
  },
  progress: {
    width: '100%',
    height: scaleSizeH(2),
    backgroundColor: 'gray',
  },
  progressView: {
    position: 'absolute',
    left: 0,
    bottom: scaleSizeH(315),
    width: '100%',
    height: scaleSizeH(56),
  },
});
