import {ScaleSize, ScaleText} from '@/util/adaptation';
import {StyleSheet, Platform, Dimensions} from 'react-native';
const statusHeight = Platform.OS == 'android' ? 0 : ScaleSize(57);
const height = Dimensions.get('window').height;
export default StyleSheet.create({
  container: {
    flex: 1,
  },
  rightIconList: {
    display: 'flex',
    justifyContent: 'flex-end',
    flexDirection: 'row',
    marginRight: ScaleSize(34),
    marginLeft: 'auto',
    marginTop: ScaleSize(26) + statusHeight,
    marginBottom: ScaleSize(45),
  },
  headIcon: {
    width: ScaleText(32),
    height: ScaleText(32),
  },
  horn: {
    width: ScaleText(72),
    height: ScaleText(60),
    borderBottomLeftRadius: ScaleText(30),
    borderTopLeftRadius: ScaleText(30),
    backgroundColor: '#000000',
    opacity: 0.2,
    position: 'absolute',
    top: ScaleSize(147),
    right: 0,
  },
  videoStatus: {
    width: ScaleText(119),
    height: ScaleText(119),
    marginTop: ScaleSize(315),
    marginLeft: 'auto',
    marginRight: 'auto',
  },
  icon: {
    width: ScaleText(36),
    height: ScaleText(30),
    marginLeft: 'auto',
    marginRight: ScaleSize(12),
  },
  open: {
    width: ScaleSize(16),
    height: ScaleSize(200),
    position: 'absolute',
    top: ScaleSize(566),
  },
  avatar: {
    position: 'absolute',
    right: ScaleSize(31),
    bottom: ScaleSize(343),
  },
  controller: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    zIndex: 20,
    backgroundColor: '#000000',
    opacity: 0.84,
    width: '100%',
    minHeight: ScaleSize(316),
    paddingLeft: ScaleSize(30),
  },
  head: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'flex-start',
    flexDirection: 'row',
    width: '100%',

  },
  comment: {
    width: ScaleSize(88),
    height: ScaleSize(36),
    borderWidth: ScaleSize(2),
    // borderColor: '#FF4646',
    borderRadius: ScaleSize(10),
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    flexDirection: 'row',
    marginRight: ScaleSize(8),
  },
  backgroundVideo: {
    width: '100%',
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    height: height - ScaleSize(316),
    backgroundColor: 'black',
    opacity: 0.8,
  },
  progress: {
    width: '100%',
    height: ScaleSize(2),
    backgroundColor: 'gray',
  },
  progressView: {
    position: 'absolute',
    left: 0,
    bottom: ScaleSize(315),
    width: '100%',
    height: ScaleSize(56),
  },
});
