import {ScaleSize, ScaleText} from '@/util/adaptation';
import {StyleSheet, Platform, Dimensions} from 'react-native';
const statusHeight = Platform.OS == 'android' ? 0 : ScaleSize(57);
const height = Dimensions.get('window').height;
export default StyleSheet.create({
  container: {
    flex: 1,
  },
  slide1: {
    backgroundColor: '#000000',
    opacity: 0.8,
    paddingTop: statusHeight + ScaleSize(26),
    height,
    display: 'flex',
    flexDirection: 'column',
  },
  header: {
    width: '100%',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    height: ScaleSize(32),
  },
  rightIconList: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'flex-end',
    flexDirection: 'row',
  },
  headIcon: {
    width: ScaleText(32),
    height: ScaleText(32),
  },
  headTit: {
    color: '#fff',
    fontSize: ScaleText(30),
    fontWeight: 'bold',
    marginLeft: ScaleSize(31),
  },
  contentText: {
    width: ScaleSize(690),
    marginLeft: ScaleSize(31),
    marginTop: ScaleSize(17),
    marginRight: ScaleSize(30),
    marginBottom: ScaleSize(15),
  },
  texts: {
    fontSize: ScaleText(26),
    color: '#FFFFFF',
  },
  starPeople: {
    fontSize: ScaleText(26),
    color: '#FF460B',
    marginLeft: ScaleSize(31),
    marginBottom: ScaleSize(17),
  },
  showMore: {
    color: '#36A8FF',
    fontSize: ScaleText(26),
  },
  horn: {
    width: ScaleSize(72),
    height: ScaleSize(60),
    borderBottomLeftRadius: ScaleSize(30),
    borderTopLeftRadius: ScaleSize(30),
    backgroundColor: '#000000',
    opacity: 0.2,
    position: 'absolute',
    top: ScaleSize(30),
    right: 0,
  },
  icon: {
    width: ScaleText(36),
    height: ScaleText(30),
    position: 'absolute',
    top: ScaleSize(44),
    right: ScaleSize(12),
  },
  open: {
    width: ScaleText(16),
    height: ScaleText(200),
    position: 'absolute',
    top: ScaleSize(259),
  },
  photoList: {
    width: '100%',
    height: ScaleSize(56),
    display: 'flex',
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'flex-start',
    position: 'absolute',
    left: ScaleSize(30),
    bottom: ScaleSize(349),
    borderRadius: ScaleSize(4),
  },
  avatar: {
    position: 'absolute',
    right: ScaleSize(31),
    bottom: ScaleSize(343),
  },
  controller: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    zIndex: 20,
    backgroundColor: '#000000',
    opacity: 0.84,
    width: '100%',
    minHeight: ScaleSize(316),
    paddingLeft: ScaleSize(30),
  },
  head: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'flex-start',
    flexDirection: 'row',
    width: '100%',
    height: ScaleSize(100),
  },
  comment: {
    width: ScaleSize(88),
    height: ScaleSize(36),
    borderWidth: ScaleSize(2),
    borderColor: '#FF4646',
    borderRadius: ScaleSize(10),
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    flexDirection: 'row',
    marginRight: ScaleSize(8),
  },
});
